version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ddd-rest-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - "5435:5432"
    volumes:
      - postgres_rest_data:/var/lib/postgresql/data
    networks:
      - ddd-rest-network

  zipkin:
    image: openzipkin/zipkin
    container_name: ddd-rest-zipkin
    ports:
      - "9414:9411"
    networks:
      - ddd-rest-network

volumes:
  postgres_rest_data:


networks:
  ddd-rest-network:
    driver: bridge
