server:
  port: 8082

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:h2:mem:clientdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9414/api/v2/spans
  thymeleaf:
    cache: false
